### ISSUE TITLE
screenshot ?

### ISSUE THREAD

**Issue by paul-hammant** [elkdanger/kanban-board#1]
One of many things in http://makeareadme.com/ that would help convert visitors into experimenters (as opposed to hitting their back buttons)

**Comment by donPuerto** [comment]
Here...
![image](https://user-images.githubusercontent.com/9329005/38248498-2619a81c-377b-11e8-8b00-0a9498ea5293.png)

https://kanban.elkdanger.co.uk/#/backlog

**Comment by paul-hammant** [comment]
Cool - hey @elkdanger - can you put this in the readme ?

**Comment by stevehobbsdev** [comment]
There absolutely should have been some screenshots. I've added some to the readme file now for you.

Thanks for the suggestion!
